# Generated by Django 2.2 on 2019-07-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_oauthrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthrelationship',
            options={'verbose_name': '第三方账号关系', 'verbose_name_plural': '第三方账号关系'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户拓展信息', 'verbose_name_plural': '用户拓展信息'},
        ),
        migrations.AlterField(
            model_name='oauthrelationship',
            name='oauth_type',
            field=models.IntegerField(choices=[(0, 'QQ'), (1, 'WeChat'), (2, 'Sina'), (3, 'Github')], default=0, verbose_name='第三方登录方式'),
        ),
    ]
