# Generated by Django 2.2 on 2019-07-16 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name': '点赞计数', 'verbose_name_plural': '点赞计数'},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name': '点赞记录', 'verbose_name_plural': '点赞记录'},
        ),
        migrations.AlterField(
            model_name='likecount',
            name='liked_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='likerecord',
            name='liked_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='点赞时间'),
        ),
        migrations.AlterField(
            model_name='likerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞人'),
        ),
    ]
