"""
Django settings for beewebsite project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '34+9we^#3ls9d2)((i4^%xscl(#+xc9k6pfvu%!tlvwk(@1@b!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.hwjbee.fun', 'www.hwjbee.fun']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  # 加载静态文件的
    'blog',
    'comment',
    'login',
    'read_statistics',
    'likes',
    'ckeditor',  # 富文本编辑
    'ckeditor_uploader',  # 图片加载
    'notifications',  # 站内提醒
    'my_notifications',  # 加载位置一定要注意前后
    'haystack',  # 全文检索
    'django.contrib.sitemaps',  # # 生成sitemap
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'beewebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 'builtins':['django.templates.static']  # static 变成内置标签，不需要load了
        },
    },
]

WSGI_APPLICATION = 'beewebsite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
import pymysql

pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'beewebsite',
        'USER': 'root',
        'PASSWORD': 'mysql',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True
# 设为false ，获取到当前的当前时间为navie类型的时间，不知道自己是哪个时区
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]

# media 配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 配置ckeditor
CKEDITOR_UPLOAD_PATH = 'upload'
CKEDITOR_CONFIGS = {
    'default': {
    },
    'comment_ckeditor': {
        'toolbar': 'custom',
        'toolbar_custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ["TextColor", "BGColor", 'RemoveFormat'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ["Smiley", "SpecialChar", 'Blockquote'],
        ],
        'width': 'auto',
        'height': '180',
        'tabSpaces': 4,
        'removePlugins': 'elementspath',
        'resize_enabled': False,
    },
}

# 每页有几篇博客的个数
EACH_PAGE_BLOGS_NUMBER = 5

# 邮箱配置
# 指定发送邮件的后端模块，大多数情况下照抄
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.163.com'
# smtp服务器端口，默认为25
EMAIL_PORT = 25
# 你在发送服务器的用户名
EMAIL_HOST_USER = 'lantaiit@163.com'
# 对应客户单授权的的密码， 不是用户的密码
EMAIL_HOST_PASSWORD = 'qq123456qq'
EMAIL_SUBJECT_PREFIX = '[个人博客]'
# 与smtp服务器通信时，是否启动tls链接（安全连接）
EMAIL_USE_TLS = True

# qq登录配置
QQ_APP_ID = '324234'  # 自己的QQ_appid
QQ_REDIRECT_URL = 'http://www.hwjbee.fun/login/login_by_qq'
QQ_STATE = 'hwjbee'
QQ_APP_KEY = 'DFKJDSLFKSDJ'  # 自己的key

# 微信登录配置
WX_APP_ID = '324234'  # 自己的WX_appid
WX_REDIRECT_URI = 'http://www.hwjbee.fun/login/login_by_weixin'
WX_STATE = 'hwjbee'
WX_APP_KEY = 'DFKJDSLFKSDJ'  # 自己的WX_key

# 微博登陆配置
WB_CLIENT_ID = '1071763530'  # 自己的微博_appid
WB_REDIRECT_URI = 'http://www.hwjbee.fum/login/login_by_weibo'
WB_ClIENT_SECRET = '8486824b5675162f100d543798c6d730'  # 自己的微博_key

# django-notifications-hq设置（站内提醒通知配置）
DJANGO_NOTIFICATIONS_CONFIG = {'USE_JSONFIELD': True}

# 全文检索配置
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'blog.whoosh_cn_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 5  # 搜出来的5个为一页
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'  # 什么时候更新索引，这里我们指定跟新文章则更新索引
